{
 "title": "Main",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dapr_app_id",
    "label": "Dapr App ID",
    "query": {
     "query": "label_values(dapr_runtime_component_loaded,app_id)"
    }
   },
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CV Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of unsatisfied CVs",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\r\n  total_number_of_unsatified_cvs / \r\n  (total_number_of_satified_cvs + total_number_of_unsatified_cvs)\r\n) * 100",
       "legendFormat": "total_number_of_unsatified_cvs"
      },
      {
       "expr": "(\r\n  total_number_of_satified_cvs / \r\n  (total_number_of_satified_cvs + total_number_of_unsatified_cvs)\r\n) * 100",
       "legendFormat": "total_number_of_satified_cvs"
      }
     ]
    },
    {
     "title": "Successful rules",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rule_runs{status=\"success\"}",
       "legendFormat": "{{rule_name}}"
      }
     ]
    },
    {
     "title": "Failed rules",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rule_runs{status=\"failure\"}",
       "legendFormat": "{{rule_name}}"
      }
     ]
    },
    {
     "title": "Total rules failed",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\r\n  sum(rule_runs{job=\"Custom-Metrics\", status=\"failure\"}) by (rule_name)\r\n  /\r\n  sum(rule_runs{job=\"Custom-Metrics\"}) by (rule_name)\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total rules success",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\r\n  sum(rule_runs{job=\"Custom-Metrics\", status=\"success\"}) by (rule_name)\r\n  /\r\n  sum(rule_runs{job=\"Custom-Metrics\"}) by (rule_name)\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total employees notified",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "notify_employee_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Overview CVs updated per month",
     "type": "timeseries",
     "description": "This shows the rate of how many CVs has been updated within the last month",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "CVs updated / Month" } },
     "targets": [
      {
       "expr": "sum by (week) (delta(cv_updated_total{job=\"Custom-Metrics\"}[4w]))",
       "legendFormat": "CVs updated per week"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Checks the status of Bouvet-CV-Service",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - label_replace(process_start_time_seconds{instance=~\"$dapr_app_id:9090\", job=\"dapr\"}, \"dapr_app\", \"$1\", \"instance\", \"(.*):9090\")",
       "legendFormat": "{{dapr_app}}"
      }
     ]
    },
    {
     "title": "Dapr sidecar status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(up{instance=~\"$dapr_app_id:9090\", job=\"dapr\"}, \"dapr_app\", \"$1\", \"instance\", \"(.*):9090\")",
       "legendFormat": "{{dapr_app}}"
      }
     ]
    },
    {
     "title": "Rule Engine execution count",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rules_engine_executed_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Rule Engine execution count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "execution/sec" } },
     "targets": [
      {
       "expr": "rate(rules_engine_executed_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total components loaded",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dapr_runtime_component_loaded{app_id=~\"$dapr_app_id\", job=\"dapr\"}",
       "legendFormat": "{{app_id}}"
      }
     ]
    },
    {
     "title": "Components loaded",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(component) (sum by(dapr_id, component) (dapr_runtime_component_init_total{app_id=~\"$dapr_app_id\", job=\"dapr\"})) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outbound request latency (App->Dapr) (95p, 75p)",
     "type": "timeseries",
     "description": "This charts shows the turn-around latency when user app calls Dapr API. For example, you can understand each statestore and service invocation performance.",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, app_id, method, path) (rate(dapr_http_server_latency_bucket{app_id=~\"$dapr_app_id\", job=\"dapr\"}[5m])))",
       "legendFormat": "{{app_id}} - {{path}}"
      }
     ]
    },
    {
     "title": "Http requests",
     "type": "bargauge",
     "description": "Displays all the requests received within each service",
     "gridPos": { "h": 23, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(http_requests_received_total{instance=~\"$dapr_app_id:80\"}, \"dapr_app\", \"$1\", \"instance\", \"(.*):80\")",
       "legendFormat": "{{endpoint}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Inbound request latency (Dapr -> App) (95p, 75p)",
     "type": "timeseries",
     "description": "This charts shows the inbound request latency from Dapr to App. You can analyze App's API endpoint performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, app_id, method, path) (rate(dapr_http_client_roundtrip_latency_bucket{app_id=~\"$dapr_app_id\", job=\"dapr\"}[5m])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, app_id, method, path) (rate(dapr_http_client_roundtrip_latency_bucket{app_id=~\"$dapr_app_id\", job=\"dapr\"}[5m])))",
       "legendFormat": "{{app_id}}- {{path}}"
      }
     ]
    },
    {
     "title": "Inbound request rate (Dapr -> App) (RPS)",
     "type": "timeseries",
     "description": "This charts shows request rate (rps) when Dapr runtime calls User app HTTP endpoints.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(app_id) (rate(dapr_http_client_completed_count{app_id=~\"$dapr_app_id\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outbound request rate (App -> Dapr) (RPS)",
     "type": "timeseries",
     "description": "This charts shows completed request rate (rps) when User app calls Dapr.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(app_id) (rate(dapr_http_server_response_count{app_id=~\"$dapr_app_id\"}[5m]))",
       "legendFormat": "{{method}} {{path}} ({{app_id}})"
      }
     ]
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory bytes allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"Custom-Metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of OS threads created",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(go_threads)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of service threads created",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(process_num_threads{instance=~\"$dapr_app_id:80\"}, \"dapr_app\", \"$1\", \"instance\", \"(.*):80\")",
     "legendFormat": "{{dapr_app}}"
    }
   ]
  }
 ]
}