apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ruleengine-secretstore
  namespace: ruleengine
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: /components/ruleengine-secrets.json
    - name: nestedSeparator
      value: ":"
    - name: multiValued
      value: "false"
