apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ruleengine-statestore-result
  namespace: ruleengine
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      value: mongo:27017
    - name: username
      secretKeyRef:
        name: MONGO_USERNAME
        key: MONGO_USERNAME
    - name: password
      secretKeyRef:
        name: MONGO_PASSWORD
        key: MONGO_PASSWORD
    - name: databaseName
      value: WorkflowResults
    - name: collectionName
      value: Bouvet-WorkflowResults
    - name: params
      value: "?authSource=admin"
auth:
  secretStore: ruleengine-secretstore
scopes:
  - bouvet-rule-engine-service
