apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
  namespace: ruleengine
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"
  metric:
    enabled: true
    exportInterval: "5s"
  exporters:
    - name: "prometheus"
      component: "prometheus-exporter"
